### PR TITLE
Added combined_realms

### PR DESCRIPTION
**Pull request by hanej**
Added the combined_realms parameter similarly to the lockout_realms parameter for nested realms.

### CODE REVIEW

**Comment by hanej** [comment]
It doesn't look like the checks failed because of the commit

**Comment by antoineco** [comment]
Indeed, it fails unconditionally since 4.6.0.

Anyway, thank for for the PR, I'll take a look ASAP.

**Comment by antoineco** [comment]
Thanks @hanej, looks good! :+1:

Could you please update the README file as well? You can pretty much duplicate the entry for the `lockout_realm` param.

**Comment by hanej** [comment]
Added to README

**Comment by antoineco** [comment]
Awesome, thanks @hanej !

**Pull request merged**
