### PR TITLE
Add parameter to set log folder mode

### PR DESCRIPTION
**Pull request by HerveMARTIN**
Keep default to 0660

### CODE REVIEW

**Comment by antoineco** [comment]
Looks good, thanks for the contribution!

**Comment by HerveMARTIN** [comment]
Would you please release this?

**Comment by antoineco** [comment]
I'll try to draft a release this weekend, I'd like to update the default package versions for all supported distros as well.

**Comment by antoineco** [comment]
@HerveMARTIN  I'm releasing v1.8.2, sorry that it took me so long!

**Pull request merged**
