### PR TITLE
Improved package handling

### PR DESCRIPTION
**Pull request by ghost**
This PR allows installing latest tomcat release from package and choose an package containing tomcat extras.

### CODE REVIEW

**Comment by antoineco** [comment]
I'm not sure to understand the motivation behind this PR.

This would destroy the possibility to install a specific Tomcat version (feature introduced recently), moreover most Linux distributions do not ship tomcat extra libraries in a package unfortunately. Fetching them from Apache servers ensures a strict version check and works on all platforms without exception. Tomcat extras could be installed from a package but this should be optional and the availability of such a package in the current package repositories should be strictly checked.

**Comment by ghost** [comment]
When a new tomcat version is released we are building two RPM packages. One tomcat and one extra package. Those packages are part of an Life Cycle Management with Katello. With Katello one version of an package is visible. Tomcat is configured via an extra Puppet module describing the whole system. This module is also managed with Katello.

Without modification i have to update an puppet modules every time a new tomcat release is available.

There are two reasons installing extras via package. We cannot fetch anything from internet and every software installed in production must be testet. This is the reason i need an RPM controlled via Katello.

If package_ensure or extra_package is unset the module works like it's unchanged.

**Comment by antoineco** [comment]
True, I didn't see the condition. I'll review it asap, thanks for another contribution!

**Comment by antoineco** [comment]
Apart from minor comments regarding my syntax preferences it looks all good :clap: Could you please rebase and force push when you're done? This way I can release as a single commit.

**Comment by antoineco** [comment]
Ping @scitechfh. 
I can also merge and squash myself if you don't have time to do it at the moment.

**Comment by ghost** [comment]
This would be nice. I have no time at the moment. Thank you.

Von: Antoine Cotten [mailto:notifications@github.com]
Gesendet: Dienstag, 15. Dezember 2015 09:59
An: antoineco/aco-tomcat aco-tomcat@noreply.github.com
Cc: Frank Holtz F.Holtz@scitech-gmbh.de
Betreff: Re: [aco-tomcat] Improved package handling (#42)

Ping @scitechfhhttps://github.com/scitechfh.
I can also merge and squash myself if you don't have time to do it at the moment.

—
Reply to this email directly or view it on GitHubhttps://github.com/antoineco/aco-tomcat/pull/42#issuecomment-164690899.

scitech it solutions GmbH
Hermann-Schumann-Str.4
16761 Hennigsdorf
GERMANY

Telefon: +49-3302-4940239
Mobil: +49-151-54445054
Fax: +49-3302-4996720
E-Mail: F.Holtz@scitech-gmbh.demailto:F.Holtz@scitech-gmbh.de
www.scitech-gmbh.dehttp://www.scitech-gmbh.de

---

scitech it solutions GmbH
Geschäftsführer: Steffen Noack • Sitz der Gesellschaft: Hennigsdorf • Registergericht: Amtsgericht Neuruppin, HRB 60 58 OPR

[http://www.scitech-gmbh.de/signatur/scitech-citrix-banner.jpg]http://www.scitech-gmbh.de/mailing/themenfokus-citrix-news-3/

---

Confidentiality Notice: This message and any attachments may contain privileged and confidential information. If you have reason to believe that you are not the intended recipient or a person responsible for delivering this information to an intended recipient, you are hereby notified that any review, dissemination, distribution, or copying of this message is strictly prohibited. Please contact the sender immediately by reply mail and destroy all copies of the original message.

**Comment by antoineco** [comment]
Thanks for the quick answer, and again for the PR!

**Comment by ghost** [comment]
Thank you for merging.

scitech it solutions GmbH
Hermann-Schumann-Str.4
16761 Hennigsdorf
GERMANY

Telefon: +49-3302-4940239
Mobil: +49-151-54445054
Fax: +49-3302-4996720
E-Mail: F.Holtz@scitech-gmbh.demailto:F.Holtz@scitech-gmbh.de
www.scitech-gmbh.dehttp://www.scitech-gmbh.de

---

scitech it solutions GmbH
Geschäftsführer: Steffen Noack • Sitz der Gesellschaft: Hennigsdorf • Registergericht: Amtsgericht Neuruppin, HRB 60 58 OPR

[http://www.scitech-gmbh.de/signatur/scitech-citrix-banner.jpg]http://www.scitech-gmbh.de/mailing/themenfokus-citrix-news-3/

---

Confidentiality Notice: This message and any attachments may contain privileged and confidential information. If you have reason to believe that you are not the intended recipient or a person responsible for delivering this information to an intended recipient, you are hereby notified that any review, dissemination, distribution, or copying of this message is strictly prohibited. Please contact the sender immediately by reply mail and destroy all copies of the original message.

**Pull request merged**
