### PR TITLE
Multi user

### PR DESCRIPTION
**Pull request by joshuabaird**
Update systemd unit ERB tempates to support multi-user per instance.

### CODE REVIEW

**Comment by joshuabaird** [comment]
I _think_ I did this the right way.

**Comment by antoineco** [comment]
That's one step but I have 2 remarks:
1. `templates/common/setenv.erb` is missing
2. To make it work on Puppet 4 you also have to "forward" the variables inside the classes which reference templates, like in the [tomcat::config class](https://github.com/antoineco/aco-tomcat/blob/master/manifests/config.pp#L10-L15). Actually `config.pp` is the only class which uses `setenv.erb`, so it's just a matter of adding 2 lines.

Apart from that it should resolve #25. Thanks Josh!

**Comment by joshuabaird** [comment]
Ok - so I need to "forward" the `tomcat_user` and `tomcat_group` params in config.pp?

**Comment by antoineco** [comment]
Yes

**Comment by joshuabaird** [comment]
Ok - how is that?

**Comment by antoineco** [comment]
Looks great, thanks!

**Pull request merged**
