### PR TITLE
Ensure files and sort attributes

### PR DESCRIPTION
**Pull request by hanej**
Some files were being created as directories so I set those resources to be explicitly files.  Also in Ruby 1.8.7 the attribute hashes in the templates are unordered which is causing Puppet to change them during each run.  The attributes are now sorted in alphabetical order to prevent Puppet from detecting changes when there weren't any.

### CODE REVIEW

**Comment by hanej** [comment]
The first two commits were left over from me getting the module to work until a permanent fix was made.  You can ignore them.

sort.each_pair is fine.  I can change that.  My Ruby isn't as strong as my Python so I expect there may be better ways to do certain things.

**Comment by antoineco** [comment]
Thanks Jason! I agree with the introduction of the `sort` method, however some commits are outdated or unnecessary. I left some comments on a per-commit basis.

Would you mind rebasing and squashing so that I can merge?

**Comment by hanej** [comment]
Sure thing

**Comment by hanej** [comment]
Submitted new pull request

**Pull request closed without merging**
