### PR TITLE
Add Environment variables to the server.xml GlobalNamingResources

### PR DESCRIPTION
**Pull request by roysjosh**
This provides Environment variables for all contexts.  Tested locally.

### CODE REVIEW

**Comment by antoineco** [comment]
:ok:
As soon as you add the extra anchor to the aforementioned URL I'll merge it. Thanks @roysjosh!

**Comment by antoineco** [comment]
ping @roysjosh

**Comment by roysjosh** [comment]
Oops, I knew I was forgetting something.  Pushed.

**Comment by antoineco** [comment]
Thanks @roysjosh :)

**Pull request merged**
