### PR TITLE
Add support for complex Host setup

### PR DESCRIPTION
**Pull request by HerveMARTIN**

### CODE REVIEW

**Comment by HerveMARTIN** [comment]
I tried to keep the backward compatibility.
I've tried it with two hosts, a context per host and no valve to see what happen when a nested component is empty.

**Comment by HerveMARTIN** [comment]
I've also added a param to choose the tomcat_user id, in case of multiple instance sharing the same nfs volume...

**Comment by HerveMARTIN** [comment]
Any update for this PR?

**Comment by antoineco** [comment]
Sorry, commits kept coming after I did the initial review, and then I forgot about it. Will try to look into it this week.

**Comment by HerveMARTIN** [comment]
Sorry for that, I had to deploy something that needed all these corrections, so I kept developping on this PR...
No more commits until you review this PR, I swear :)

**Comment by HerveMARTIN** [comment]
@antoineco any chance you could check this PR soon?

**Comment by antoineco** [comment]
Again, I'm very sorry for making you wait for so long. The truth is I haven't used Puppet in 3 years now and am so busy with completely different topics now that setting up a test environment will require more work than I want to dedicate to this module.

I will merge this and release the last version of aco-tomcat based on the fact that you didn't break the API and already  contributed great things to this module before. Thanks a lot for engaging with this project and for your patience :raised_hands:

**Pull request merged**
