### PR TITLE
Rolling back systemd management for Debian 8/9

### PR DESCRIPTION
**Pull request by geekix**
Hello,

It seems that enabling systemd for Debian 8/9 causes more problems then I expected. There are a few mores cases to take care of before it can be fully functionnal (my bad on this one).

I am rolling back the modifications in the params.pp manifests while I work on a new patch.

Adding the run levels in the init script is enough to make systemd managing the tomcat process using the init.d script.

### CODE REVIEW

**Comment by antoineco** [comment]
Looks like you need to rebase your branch on the current `master`. This changeset produces an [unexpected result](https://github.com/antoineco/aco-tomcat/pull/93/files).

Could you describe the issues you're facing? I don't have a Debian machine with systemd at hand right now.

**Comment by geekix** [comment]
I'm new to github, so please forgive any bad action ^^
I will do more tests and post here the issues I'm facing. Thanks for your time

**Comment by antoineco** [comment]
@geekix we should not include the Debian script as is, it will not work on other distributions.

**Comment by geekix** [comment]
@antoineco I agree, I was just testing something, I did not mean to go live with this (again, I'm still a newbie with git =s)

**Pull request closed without merging**
